In [1]:
#pip install numpy

In [2]:
#pip install pandas

In [3]:
#pip install matplotlib

In [4]:
#pip install scikit-learn

In [5]:
import numpy as nump
import pandas as pd
import matplotlib.pyplot as py
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
%matplotlib inline


In [6]:
import warnings
warnings.simplefilter('ignore')

In [7]:
#Read Dataset
data=pd.read_csv('placement.csv')
data

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [8]:
#split the data set
x=data.iloc[:,0].values.reshape(-1,1)
y=data.iloc[:,1].values.reshape(-1,1)

In [9]:
x

array([[6.89],
       [5.12],
       [7.82],
       [7.42],
       [6.94],
       [7.89],
       [6.73],
       [6.75],
       [6.09],
       [8.31],
       [5.32],
       [6.61],
       [8.94],
       [6.93],
       [7.73],
       [7.25],
       [6.84],
       [5.38],
       [6.94],
       [7.48],
       [7.28],
       [6.85],
       [6.14],
       [6.19],
       [6.53],
       [7.28],
       [8.31],
       [5.42],
       [5.94],
       [7.15],
       [7.36],
       [8.1 ],
       [6.96],
       [6.35],
       [7.34],
       [6.87],
       [5.99],
       [5.9 ],
       [8.62],
       [7.43],
       [9.38],
       [6.89],
       [5.95],
       [7.66],
       [5.09],
       [7.87],
       [6.07],
       [5.84],
       [8.63],
       [8.87],
       [9.58],
       [9.26],
       [8.37],
       [6.47],
       [6.86],
       [8.2 ],
       [5.84],
       [6.6 ],
       [6.92],
       [7.56],
       [5.61],
       [5.48],
       [6.34],
       [9.16],
       [7.36],
       [7.6 ],
       [5.

In [10]:
y

array([[3.26],
       [1.98],
       [3.25],
       [3.67],
       [3.57],
       [2.99],
       [2.6 ],
       [2.48],
       [2.31],
       [3.51],
       [1.86],
       [2.6 ],
       [3.65],
       [2.89],
       [3.42],
       [3.23],
       [2.35],
       [2.09],
       [2.98],
       [2.83],
       [3.16],
       [2.93],
       [2.3 ],
       [2.48],
       [2.71],
       [3.65],
       [3.42],
       [2.16],
       [2.24],
       [3.49],
       [3.26],
       [3.89],
       [3.08],
       [2.73],
       [3.42],
       [2.87],
       [2.84],
       [2.43],
       [4.36],
       [3.33],
       [4.02],
       [2.7 ],
       [2.54],
       [2.76],
       [1.86],
       [3.58],
       [2.26],
       [3.26],
       [4.09],
       [4.62],
       [4.43],
       [3.79],
       [4.11],
       [2.61],
       [3.09],
       [3.39],
       [2.74],
       [1.94],
       [3.09],
       [3.31],
       [2.19],
       [1.61],
       [2.09],
       [4.25],
       [2.92],
       [3.81],
       [1.

In [11]:
#library used for train,test
#from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [12]:
x_train

array([[6.37],
       [7.11],
       [8.22],
       [7.48],
       [7.94],
       [7.9 ],
       [6.86],
       [8.93],
       [9.26],
       [7.61],
       [7.19],
       [7.11],
       [7.14],
       [6.71],
       [6.17],
       [6.42],
       [7.77],
       [7.73],
       [5.42],
       [6.76],
       [6.26],
       [6.07],
       [7.91],
       [6.93],
       [7.76],
       [6.34],
       [7.82],
       [7.56],
       [5.64],
       [7.21],
       [7.66],
       [5.32],
       [7.89],
       [8.44],
       [5.89],
       [8.15],
       [7.04],
       [5.91],
       [6.79],
       [8.58],
       [5.95],
       [7.28],
       [9.58],
       [6.89],
       [5.83],
       [8.18],
       [6.63],
       [7.36],
       [8.13],
       [6.89],
       [7.3 ],
       [8.87],
       [8.63],
       [4.79],
       [6.93],
       [7.3 ],
       [6.19],
       [7.84],
       [6.1 ],
       [7.28],
       [7.25],
       [6.59],
       [7.62],
       [8.37],
       [7.95],
       [6.94],
       [7.

In [13]:
x_test

array([[6.94],
       [6.22],
       [6.33],
       [7.69],
       [7.09],
       [5.88],
       [7.89],
       [6.07],
       [8.94],
       [7.37],
       [5.48],
       [7.33],
       [6.19],
       [7.08],
       [7.63],
       [6.75],
       [6.35],
       [6.68],
       [5.9 ],
       [6.85],
       [7.28],
       [5.84],
       [7.87],
       [8.71],
       [5.61],
       [5.1 ],
       [7.14],
       [6.31],
       [5.12],
       [5.09],
       [6.84],
       [8.2 ],
       [6.3 ],
       [5.42],
       [6.14],
       [8.11],
       [7.29],
       [6.94],
       [8.44],
       [6.13],
       [7.2 ],
       [5.11],
       [8.31],
       [6.94],
       [8.65],
       [9.16],
       [6.09],
       [6.97],
       [7.4 ],
       [4.85],
       [7.47],
       [6.06],
       [7.88],
       [5.98],
       [8.28],
       [6.53],
       [7.36],
       [7.13],
       [9.38],
       [5.84]])

In [14]:
y_train

array([[2.01],
       [2.61],
       [3.89],
       [2.83],
       [3.99],
       [4.  ],
       [3.09],
       [3.91],
       [3.79],
       [2.77],
       [2.4 ],
       [2.66],
       [3.13],
       [3.52],
       [2.42],
       [2.72],
       [4.06],
       [3.42],
       [2.16],
       [3.18],
       [2.44],
       [2.26],
       [3.89],
       [2.46],
       [3.54],
       [2.09],
       [3.25],
       [3.31],
       [2.1 ],
       [3.24],
       [2.76],
       [1.86],
       [3.67],
       [4.03],
       [2.57],
       [3.63],
       [3.5 ],
       [2.6 ],
       [3.08],
       [4.1 ],
       [3.04],
       [3.48],
       [4.43],
       [3.26],
       [2.42],
       [3.76],
       [2.79],
       [2.92],
       [3.6 ],
       [2.7 ],
       [2.94],
       [4.62],
       [4.09],
       [1.48],
       [2.89],
       [3.33],
       [2.48],
       [3.47],
       [2.6 ],
       [3.16],
       [3.23],
       [2.21],
       [3.74],
       [4.11],
       [4.14],
       [3.15],
       [3.

In [15]:
y_test

array([[2.98],
       [2.87],
       [2.59],
       [3.83],
       [3.64],
       [2.08],
       [2.99],
       [2.46],
       [3.65],
       [3.08],
       [1.61],
       [3.16],
       [2.72],
       [2.85],
       [3.44],
       [2.48],
       [2.73],
       [2.49],
       [2.43],
       [3.44],
       [2.72],
       [2.18],
       [3.58],
       [4.08],
       [2.19],
       [2.3 ],
       [3.03],
       [3.18],
       [2.01],
       [1.86],
       [2.35],
       [3.39],
       [2.73],
       [2.25],
       [2.3 ],
       [4.06],
       [3.12],
       [3.57],
       [3.49],
       [2.19],
       [2.83],
       [1.63],
       [3.42],
       [2.37],
       [3.52],
       [4.25],
       [2.31],
       [3.28],
       [2.88],
       [1.54],
       [3.34],
       [2.31],
       [3.14],
       [2.84],
       [3.67],
       [2.71],
       [3.26],
       [2.93],
       [4.02],
       [2.74]])

In [16]:
#library used for linear regression
#from sklearn.linear_model import LinearRegression
lm=LinearRegression()

In [17]:
lm.fit(x_train,y_train)

LinearRegression()

In [18]:
#predict value with independent dataset
predictvalue=lm.predict(x_test)

In [19]:
predictvalue

array([[2.98741886],
       [2.56299265],
       [2.62783555],
       [3.4295295 ],
       [3.07584099],
       [2.36256917],
       [3.54742567],
       [2.47457053],
       [4.16638056],
       [3.24089563],
       [2.12677683],
       [3.2173164 ],
       [2.54530823],
       [3.06994618],
       [3.39416065],
       [2.8754175 ],
       [2.63962516],
       [2.83415384],
       [2.37435878],
       [2.93436559],
       [3.18784235],
       [2.33898993],
       [3.53563605],
       [4.03079997],
       [2.20340934],
       [1.9027741 ],
       [3.10531503],
       [2.61604593],
       [1.91456372],
       [1.8968793 ],
       [2.92847078],
       [3.73016473],
       [2.61015112],
       [2.09140798],
       [2.51583419],
       [3.67711146],
       [3.19373716],
       [2.98741886],
       [3.87164014],
       [2.50993938],
       [3.14068389],
       [1.90866891],
       [3.79500763],
       [2.98741886],
       [3.99543112],
       [4.29606635],
       [2.48636014],
       [3.005

In [20]:
#compare available data with predicted data
compare=pd.DataFrame(x_test,columns=['CGPA'])

In [21]:
compare["AVLDATA"]=y_test
compare['Predictdata']=predictvalue

In [22]:
compare

CGPA  AVLDATA  Predictdata
0   6.94     2.98     2.987419
1   6.22     2.87     2.562993
2   6.33     2.59     2.627836
3   7.69     3.83     3.429530
4   7.09     3.64     3.075841
5   5.88     2.08     2.362569
6   7.89     2.99     3.547426
7   6.07     2.46     2.474571
8   8.94     3.65     4.166381
9   7.37     3.08     3.240896
10  5.48     1.61     2.126777
11  7.33     3.16     3.217316
12  6.19     2.72     2.545308
13  7.08     2.85     3.069946
14  7.63     3.44     3.394161
15  6.75     2.48     2.875418
16  6.35     2.73     2.639625
17  6.68     2.49     2.834154
18  5.90     2.43     2.374359
19  6.85     3.44     2.934366
20  7.28     2.72     3.187842
21  5.84     2.18     2.338990
22  7.87     3.58     3.535636
23  8.71     4.08     4.030800
24  5.61     2.19     2.203409
25  5.10     2.30     1.902774
26  7.14     3.03     3.105315
27  6.31     3.18     2.616046
28  5.12     2.01     1.914564
29  5.09     1.86     1.896879
30  6.84     2.35     2.928471
31  8.20     3.39     3.730165
32  6.30     2.73     2.610151
33  5.42     2.25     2.091408
34  6.14     2.30     2.515834
35  8.11     4.06     3.677111
36  7.29     3.12     3.193737
37  6.94     3.57     2.987419
38  8.44     3.49     3.871640
39  6.13     2.19     2.509939
40  7.20     2.83     3.140684
41  5.11     1.63     1.908669
42  8.31     3.42     3.795008
43  6.94     2.37     2.987419
44  8.65     3.52     3.995431
45  9.16     4.25     4.296066
46  6.09     2.31     2.486360
47  6.97     3.28     3.005103
48  7.40     2.88     3.258580
49  4.85     1.54     1.755404
50  7.47     3.34     3.299844
51  6.06     2.31     2.468676
52  7.88     3.14     3.541531
53  5.98     2.84     2.421517
54  8.28     3.67     3.777323
55  6.53     2.71     2.745732
56  7.36     3.26     3.235001
57  7.13     2.93     3.099420
58  9.38     4.02     4.425752
59  5.84     2.74     2.338990

In [23]:
#library used for find error among predicted data
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [24]:
mean_squared_error(y_test,predictvalue)

0.10197736592874904

In [25]:
mean_absolute_error(y_test,predictvalue)

0.2603739664236009

In [26]:
r2_score(y_test,predictvalue)

0.7509091646328012