##  Categorical Data:
#### Handling missing values,Normalization


In [1]:
# pip install scikit-learn

In [2]:
from sklearn. impute import SimpleImputer

In [3]:
import pandas as pd
import numpy as np
import seaborn as sb
from matplotlib import pyplot as py
%matplotlib inline

In [4]:
sb.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [5]:
tip=sb.load_dataset('tips')
t=tip.tail(15)
t

total_bill   tip     sex smoker   day    time  size
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [6]:
new_data=t.smoker.map({'Yes':0,'No':1})
new_data

229    0
230    0
231    0
232    1
233    1
234    0
235    1
236    0
237    0
238    1
239    1
240    0
241    0
242    1
243    1
Name: smoker, dtype: category
Categories (2, int64): [0, 1]

In [7]:
t['Code']=new_data
t

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9320\2340491727.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t['Code']=new_data


total_bill   tip     sex smoker   day    time  size Code
229       22.12  2.88  Female    Yes   Sat  Dinner     2    0
230       24.01  2.00    Male    Yes   Sat  Dinner     4    0
231       15.69  3.00    Male    Yes   Sat  Dinner     3    0
232       11.61  3.39    Male     No   Sat  Dinner     2    1
233       10.77  1.47    Male     No   Sat  Dinner     2    1
234       15.53  3.00    Male    Yes   Sat  Dinner     2    0
235       10.07  1.25    Male     No   Sat  Dinner     2    1
236       12.60  1.00    Male    Yes   Sat  Dinner     2    0
237       32.83  1.17    Male    Yes   Sat  Dinner     2    0
238       35.83  4.67  Female     No   Sat  Dinner     3    1
239       29.03  5.92    Male     No   Sat  Dinner     3    1
240       27.18  2.00  Female    Yes   Sat  Dinner     2    0
241       22.67  2.00    Male    Yes   Sat  Dinner     2    0
242       17.82  1.75    Male     No   Sat  Dinner     2    1
243       18.78  3.00  Female     No  Thur  Dinner     2    1

In [8]:
data=pd.DataFrame({'Salary':[30000,30000,100000,45000,'NaN',40000],'Age':[19,'NaN',20,20,21,19]})
data

Salary  Age
0   30000   19
1   30000  NaN
2  100000   20
3   45000   20
4     NaN   21
5   40000   19

In [9]:
imputers=SimpleImputer(missing_values=np.NaN,strategy='mean')

In [10]:
imputers.fit(data)

SimpleImputer()

In [11]:
i=imputers.transform(data)
i

array([[3.00e+04, 1.90e+01],
       [3.00e+04, 1.98e+01],
       [1.00e+05, 2.00e+01],
       [4.50e+04, 2.00e+01],
       [4.90e+04, 2.10e+01],
       [4.00e+04, 1.90e+01]])

In [12]:
imputer1=SimpleImputer(missing_values=np.NaN,strategy='median')
imputer1.fit(data)

SimpleImputer(strategy='median')

In [13]:
j=imputer1.transform(data)
j

array([[3.0e+04, 1.9e+01],
       [3.0e+04, 2.0e+01],
       [1.0e+05, 2.0e+01],
       [4.5e+04, 2.0e+01],
       [4.0e+04, 2.1e+01],
       [4.0e+04, 1.9e+01]])

In [14]:
imputer2=SimpleImputer(missing_values=np.NaN,strategy='most_frequent')
imputer2.fit(data)

SimpleImputer(strategy='most_frequent')

In [15]:
k=imputer2.transform(data)
k

array([[30000, 19],
       [30000, 'NaN'],
       [100000, 20],
       [45000, 20],
       ['NaN', 21],
       [40000, 19]], dtype=object)

In [16]:
imputer3=SimpleImputer(missing_values=np.NaN,strategy='constant')
imputer3.fit(data)

SimpleImputer(strategy='constant')

In [17]:
k1=imputer3.transform(data)
k1

array([[30000, 19],
       [30000, 'NaN'],
       [100000, 20],
       [45000, 20],
       ['NaN', 21],
       [40000, 19]], dtype=object)