In [1]:
import numpy as np

In [2]:
a=np.array([(1,2,3),(6,7,8),(4,5,9)])

In [3]:
print(a)
type(a)

[[1 2 3]
 [6 7 8]
 [4 5 9]]


numpy.ndarray

In [4]:
t=np.transpose(a)
print(t)

[[1 6 4]
 [2 7 5]
 [3 8 9]]


In [5]:
a.ravel()

array([1, 2, 3, 6, 7, 8, 4, 5, 9])

In [6]:
zero=np.zeros((2,2))

In [7]:
print(zero)

[[0. 0.]
 [0. 0.]]


In [8]:
one=np.ones((2,2))
one

array([[1., 1.],
       [1., 1.]])

In [9]:
#Append
np.append(zero,one)

array([0., 0., 0., 0., 1., 1., 1., 1.])

In [10]:
arr=np.array([(1,2,3,4,5,6,7)])

In [11]:
#Insert
ins=np.insert(arr,2,4)
ins

array([1, 2, 4, 3, 4, 5, 6, 7])

In [12]:
#Concatenate
np.concatenate((arr,arr),axis=None)

array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])

## Stack 

In [13]:
np.hstack((a,a))

array([[1, 2, 3, 1, 2, 3],
       [6, 7, 8, 6, 7, 8],
       [4, 5, 9, 4, 5, 9]])

In [14]:
np.vstack((a,a))

array([[1, 2, 3],
       [6, 7, 8],
       [4, 5, 9],
       [1, 2, 3],
       [6, 7, 8],
       [4, 5, 9]])

In [15]:
#Split
np.vsplit(a,3)

[array([[1, 2, 3]]), array([[6, 7, 8]]), array([[4, 5, 9]])]

In [16]:
#Empty matrix
np.empty((2,2))

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [17]:
#Random number
rand=np.random.random((10,20))
rand

array([[0.13338864, 0.89632909, 0.20512297, 0.1792928 , 0.13128516,
        0.06139903, 0.40982282, 0.32208531, 0.00983295, 0.36752998,
        0.94576219, 0.70541391, 0.71172986, 0.77222223, 0.18835675,
        0.50564886, 0.17397149, 0.88335338, 0.98592112, 0.63139154],
       [0.96340849, 0.20513682, 0.75606802, 0.66215713, 0.30145895,
        0.7163545 , 0.35930206, 0.78193117, 0.24079796, 0.00699464,
        0.39571595, 0.55453735, 0.19976504, 0.04848519, 0.41709589,
        0.30213315, 0.5292486 , 0.03019046, 0.19756519, 0.55813149],
       [0.51571962, 0.72058524, 0.60159969, 0.74326754, 0.01765363,
        0.10637691, 0.4984983 , 0.8223149 , 0.55543164, 0.31886463,
        0.84249306, 0.35024366, 0.36974257, 0.47909836, 0.43283775,
        0.38969808, 0.63450277, 0.86202936, 0.06021514, 0.539274  ],
       [0.74888923, 0.33250447, 0.93373024, 0.78492232, 0.26068367,
        0.32026517, 0.69951408, 0.21912681, 0.02504457, 0.42609689,
        0.57531038, 0.90410574, 0.3317947 , 0