In [1]:
#pip install numpy

In [2]:
#pip install pandas

In [3]:
#pip install matplotlib

In [4]:
#pip install scikit-learn

In [5]:
import numpy as nump
import pandas as pd
import matplotlib.pyplot as py
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
%matplotlib inline


In [6]:
import warnings
warnings.simplefilter('ignore')

In [7]:
data=pd.read_csv('Admission_Predict_Ver1.1.csv')
data

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1        337          118                  4  4.5  4.5  9.65   
1             2        324          107                  4  4.0  4.5  8.87   
2             3        316          104                  3  3.0  3.5  8.00   
3             4        322          110                  3  3.5  2.5  8.67   
4             5        314          103                  2  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496        332          108                  5  4.5  4.0  9.02   
496         497        337          117                  5  5.0  5.0  9.87   
497         498        330          120                  5  4.5  5.0  9.56   
498         499        312          103                  4  4.0  5.0  8.43   
499         500        327          113                  4  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [8]:
dataset=data.drop(['TOEFL Score','University Rating','SOP','LOR','GRE Score','Research','Serial No.'],axis=1)
dataset

CGPA  Chance of Admit
0    9.65             0.92
1    8.87             0.76
2    8.00             0.72
3    8.67             0.80
4    8.21             0.65
..    ...              ...
495  9.02             0.87
496  9.87             0.96
497  9.56             0.93
498  8.43             0.73
499  9.04             0.84

[500 rows x 2 columns]

In [9]:
x=dataset.iloc[:,0].values.reshape(-1,1)
y=dataset.iloc[:,1].values.reshape(-1,1)

In [10]:
x

array([[9.65],
       [8.87],
       [8.  ],
       [8.67],
       [8.21],
       [9.34],
       [8.2 ],
       [7.9 ],
       [8.  ],
       [8.6 ],
       [8.4 ],
       [9.  ],
       [9.1 ],
       [8.  ],
       [8.2 ],
       [8.3 ],
       [8.7 ],
       [8.  ],
       [8.8 ],
       [8.5 ],
       [7.9 ],
       [8.4 ],
       [9.5 ],
       [9.7 ],
       [9.8 ],
       [9.6 ],
       [8.8 ],
       [7.5 ],
       [7.2 ],
       [7.3 ],
       [8.1 ],
       [8.3 ],
       [9.4 ],
       [9.6 ],
       [9.8 ],
       [9.2 ],
       [8.4 ],
       [7.8 ],
       [7.5 ],
       [7.7 ],
       [8.  ],
       [8.2 ],
       [8.5 ],
       [9.1 ],
       [9.4 ],
       [9.1 ],
       [9.3 ],
       [9.7 ],
       [8.85],
       [8.4 ],
       [8.3 ],
       [7.9 ],
       [8.  ],
       [8.1 ],
       [8.  ],
       [7.7 ],
       [7.4 ],
       [7.6 ],
       [6.8 ],
       [8.3 ],
       [8.1 ],
       [8.2 ],
       [8.2 ],
       [8.5 ],
       [8.7 ],
       [8.92],
       [9.

In [11]:
y

array([[0.92],
       [0.76],
       [0.72],
       [0.8 ],
       [0.65],
       [0.9 ],
       [0.75],
       [0.68],
       [0.5 ],
       [0.45],
       [0.52],
       [0.84],
       [0.78],
       [0.62],
       [0.61],
       [0.54],
       [0.66],
       [0.65],
       [0.63],
       [0.62],
       [0.64],
       [0.7 ],
       [0.94],
       [0.95],
       [0.97],
       [0.94],
       [0.76],
       [0.44],
       [0.46],
       [0.54],
       [0.65],
       [0.74],
       [0.91],
       [0.9 ],
       [0.94],
       [0.88],
       [0.64],
       [0.58],
       [0.52],
       [0.48],
       [0.46],
       [0.49],
       [0.53],
       [0.87],
       [0.91],
       [0.88],
       [0.86],
       [0.89],
       [0.82],
       [0.78],
       [0.76],
       [0.56],
       [0.78],
       [0.72],
       [0.7 ],
       [0.64],
       [0.64],
       [0.46],
       [0.36],
       [0.42],
       [0.48],
       [0.47],
       [0.54],
       [0.56],
       [0.52],
       [0.55],
       [0.

In [12]:
#from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [13]:
x_train

array([[9.46],
       [8.79],
       [9.76],
       [7.95],
       [8.2 ],
       [7.88],
       [8.56],
       [9.17],
       [8.65],
       [8.69],
       [7.64],
       [7.9 ],
       [8.16],
       [8.  ],
       [7.86],
       [9.22],
       [7.66],
       [9.66],
       [9.06],
       [9.36],
       [8.13],
       [8.4 ],
       [9.28],
       [9.17],
       [7.94],
       [7.89],
       [8.3 ],
       [8.02],
       [8.65],
       [8.13],
       [8.34],
       [9.01],
       [9.11],
       [7.7 ],
       [8.18],
       [8.12],
       [8.53],
       [7.57],
       [8.76],
       [8.68],
       [8.76],
       [8.  ],
       [8.9 ],
       [8.8 ],
       [8.62],
       [8.21],
       [8.8 ],
       [8.12],
       [9.02],
       [9.34],
       [9.36],
       [8.26],
       [8.77],
       [8.22],
       [8.36],
       [9.5 ],
       [9.22],
       [7.9 ],
       [9.15],
       [8.2 ],
       [8.49],
       [8.03],
       [8.7 ],
       [8.67],
       [8.33],
       [9.5 ],
       [8.

In [14]:
x_test

array([[7.92],
       [9.12],
       [8.9 ],
       [9.08],
       [8.13],
       [8.3 ],
       [7.86],
       [8.5 ],
       [7.9 ],
       [8.75],
       [8.15],
       [8.57],
       [8.24],
       [9.  ],
       [9.07],
       [7.89],
       [8.88],
       [8.12],
       [8.89],
       [7.8 ],
       [7.65],
       [8.34],
       [7.68],
       [9.38],
       [9.1 ],
       [8.54],
       [8.4 ],
       [7.46],
       [8.  ],
       [8.07],
       [8.74],
       [7.28],
       [8.47],
       [8.98],
       [7.65],
       [7.69],
       [9.18],
       [9.25],
       [8.17],
       [8.37],
       [8.27],
       [9.3 ],
       [9.23],
       [8.56],
       [8.72],
       [8.87],
       [9.78],
       [9.14],
       [8.03],
       [8.25],
       [8.36],
       [8.04],
       [8.13],
       [8.96],
       [8.56],
       [9.1 ],
       [7.86],
       [9.23],
       [8.23],
       [8.24],
       [7.54],
       [9.45],
       [8.1 ],
       [9.86],
       [8.76],
       [8.26],
       [8.

In [15]:
y_train

array([[0.91],
       [0.72],
       [0.96],
       [0.67],
       [0.75],
       [0.59],
       [0.72],
       [0.85],
       [0.71],
       [0.77],
       [0.49],
       [0.68],
       [0.71],
       [0.5 ],
       [0.57],
       [0.86],
       [0.38],
       [0.94],
       [0.79],
       [0.93],
       [0.74],
       [0.78],
       [0.89],
       [0.86],
       [0.49],
       [0.59],
       [0.42],
       [0.61],
       [0.71],
       [0.56],
       [0.7 ],
       [0.82],
       [0.86],
       [0.64],
       [0.64],
       [0.67],
       [0.69],
       [0.37],
       [0.73],
       [0.84],
       [0.77],
       [0.78],
       [0.74],
       [0.76],
       [0.76],
       [0.65],
       [0.79],
       [0.73],
       [0.81],
       [0.9 ],
       [0.9 ],
       [0.62],
       [0.82],
       [0.62],
       [0.57],
       [0.94],
       [0.68],
       [0.64],
       [0.82],
       [0.61],
       [0.66],
       [0.61],
       [0.52],
       [0.73],
       [0.74],
       [0.96],
       [0.

In [16]:
y_test

array([[0.64],
       [0.85],
       [0.8 ],
       [0.91],
       [0.68],
       [0.54],
       [0.54],
       [0.65],
       [0.52],
       [0.79],
       [0.65],
       [0.74],
       [0.64],
       [0.79],
       [0.89],
       [0.43],
       [0.81],
       [0.73],
       [0.8 ],
       [0.58],
       [0.57],
       [0.74],
       [0.6 ],
       [0.93],
       [0.88],
       [0.67],
       [0.7 ],
       [0.57],
       [0.48],
       [0.64],
       [0.69],
       [0.47],
       [0.57],
       [0.87],
       [0.39],
       [0.53],
       [0.84],
       [0.89],
       [0.63],
       [0.7 ],
       [0.72],
       [0.86],
       [0.91],
       [0.75],
       [0.74],
       [0.76],
       [0.96],
       [0.81],
       [0.6 ],
       [0.62],
       [0.69],
       [0.68],
       [0.59],
       [0.8 ],
       [0.71],
       [0.78],
       [0.69],
       [0.89],
       [0.67],
       [0.58],
       [0.44],
       [0.89],
       [0.53],
       [0.92],
       [0.66],
       [0.73],
       [0.

In [17]:
#from sklearn.linear_model import LinearRegression
lm=LinearRegression()

In [18]:
lm.fit(x_train,y_train)

LinearRegression()

In [19]:
predictvalue=lm.predict(x_test)

In [20]:
predictvalue

array([[0.58491157],
       [0.83407395],
       [0.78839418],
       [0.82576854],
       [0.62851498],
       [0.66381299],
       [0.57245345],
       [0.70534005],
       [0.58075886],
       [0.75724888],
       [0.63266769],
       [0.71987452],
       [0.65135487],
       [0.80915771],
       [0.82369218],
       [0.57868251],
       [0.78424147],
       [0.62643863],
       [0.78631783],
       [0.55999533],
       [0.52885003],
       [0.6721184 ],
       [0.53507909],
       [0.88805913],
       [0.82992124],
       [0.71364546],
       [0.68457652],
       [0.48939932],
       [0.60152239],
       [0.61605686],
       [0.75517253],
       [0.45202496],
       [0.69911099],
       [0.80500501],
       [0.52885003],
       [0.53715544],
       [0.84653207],
       [0.86106654],
       [0.6368204 ],
       [0.67834746],
       [0.65758393],
       [0.87144831],
       [0.85691384],
       [0.71779817],
       [0.75101982],
       [0.78216512],
       [0.97111326],
       [0.838

In [21]:
compare=pd.DataFrame(x_test,columns=['CGPA'])

In [22]:
compare["AVLDATA"]=y_test
compare['Predictdata']=predictvalue

In [23]:
compare

CGPA  AVLDATA  Predictdata
0   7.92     0.64     0.584912
1   9.12     0.85     0.834074
2   8.90     0.80     0.788394
3   9.08     0.91     0.825769
4   8.13     0.68     0.628515
..   ...      ...          ...
95  9.62     0.95     0.937892
96  7.40     0.64     0.476941
97  7.79     0.53     0.557919
98  8.10     0.48     0.622286
99  8.16     0.64     0.634744

[100 rows x 3 columns]

In [24]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [25]:
mean_squared_error(y_test,predictvalue)

0.004463232500088233

In [26]:
mean_absolute_error(y_test,predictvalue)

0.04932036975238603

In [27]:
r2_score(y_test,predictvalue)

0.7444433788008283